skip_ssl: true

ansible_host: "127.0.0.1"
ansible_port: "2222"
ansible_user: "vagrant"
ansible_ssh_private_key_file: "../.vagrant/machines/local/virtualbox/private_key"

app_name: "rewind-local"
db_name: "{{ app_name }}"
db_user: "{{ app_name }}"

hostname: "rewind-local.skif.fr"
